Fixed FILESYSTEM_LIST
Changed FILESYSTEM_LIST="${SCRIPTSDIR}/rootfs_lists/${2}" to FILESYSTEM_LIST="${2}" because entering the command ./scripts/mk_container.sh -l scripts/rootfs_lists/default.txt -n "My_first_container" -v 1.0 will result in -> Creating archive /home/user/M3_Container/working/update/rootfs.tar containing the root file system
   ERROR: the given list file "./scripts/rootfs_lists/scripts/rootfs_lists/default.txt" does not exist